import Foundation

registerConfigTests()
registerPolicyTests()
registerManagementTests()
registerLogTests()
registerCleanupTests()
registerHelperTests()
registerLogTrustTests()
registerPersistentHelperTests()
registerUninstallHelperTests()
registerManagementProtocolTests()
registerConnectionTests()
registerProfileTests()
registerProfileOptionsTests()
registerAppLogicTests()
registerManagerTests()
registerScriptManagerTests()
registerPowerTests()
registerProfileOptionsManagerTests()
registerConnectionDraftTests()
registerDNSTests()
registerLeakTests()
registerProtectionTests()
registerProtectionHelperTests()
registerTunnelRequestTests()
registerPrivsepHelperTests()
registerRouteGetTests()
registerSplitDNSTests()
registerImportTests()
registerPersistentAppTests()
registerLocalizationTests()
registerUninstallAppTests()
registerLogViewTests()
registerHighlightTests()
registerLicenseTests()
registerIconTests()
registerMenuIconTests()

exit(runTests(filters: Array(CommandLine.arguments.dropFirst())))
