import Foundation

/// What the protection engine has to enforce right now. The helper fills it
/// from what it knows itself (its tunnels, its blocks); the app only switches
/// features on and off.
public struct ProtectionState: Equatable, Sendable {
    /// A kill switch that fired: its owner's traffic outside the tunnels is blocked.
    public struct Lock: Equatable, Sendable {
        public var owner: UInt32
        public var allowLAN: Bool
        public init(owner: UInt32, allowLAN: Bool) {
            self.owner = owner
            self.allowLAN = allowLAN
        }
    }

    /// utun devices of MugVPN's tunnels: traffic through them always passes.
    public var tunnels: [String] = []
    /// Kill switches that fired. Each blocks only its owner's sockets (TCP and
    /// UDP): one user's drop does not cut the others off, and openvpn (root)
    /// can always reach its servers.
    public var locks: [Lock] = []
    /// While a tunnel takes all traffic (routes are the whole Mac's): IPv6 outside the tunnels is blocked.
    public var blockIPv6 = false
    /// While a tunnel takes all traffic: DNS (port 53) outside the tunnels is blocked.
    public var dnsOnlyTunnels = false
    /// Tunnels of standard users: only their owner's sockets (and the system resolver's,
    /// for the owner's own domains) send into them; nobody else's traffic can be taken.
    public var ownTraffic: [OwnTunnel] = []
    public struct OwnTunnel: Equatable, Sendable {
        public var device: String
        public var owner: UInt32
        public init(device: String, owner: UInt32) {
            self.device = device
            self.owner = owner
        }
    }

    public init() {}

    public var isEmpty: Bool { locks.isEmpty && !blockIPv6 && !dnsOnlyTunnels && ownTraffic.isEmpty }
}

/// PF rules for MugVPN's anchor. Built only from validated values: interface
/// names `utunN` and numeric user ids; anything else is left out.
public enum PFRules {
    /// Under Apple's anchor point, which the stock /etc/pf.conf loads.
    public static let anchorName = "com.apple/mugvpn"

    static let lan = ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "169.254.0.0/16", "224.0.0.0/4",
                      "fe80::/10", "fc00::/7", "ff00::/8"]

    public static func anchor(_ s: ProtectionState) -> String {
        guard !s.isEmpty else { return "" }
        var r = ["# MugVPN protection (generated by the helper)"]
        let locks = s.locks.filter { $0.owner != 0 && $0.owner != UInt32.max }
        if locks.contains(where: \.allowLAN) { r.append("table <mugvpn_lan> const { \(lan.joined(separator: " ")) }") }
        r.append("pass out quick on lo0 all")
        // mDNSResponder (_mdnsresponder, 65) asks the owner's DNS servers for the owner's domains.
        for t in s.ownTraffic where isUtun(t.device) && t.owner != 0 && t.owner != UInt32.max {
            r.append("pass out quick on \(t.device) proto { tcp udp } user { \(t.owner) 65 }")
            r.append("block return out quick on \(t.device) proto { tcp udp } all")
        }
        let tunnels = Array(Set(s.tunnels.filter(isUtun))).sorted()
        if !tunnels.isEmpty { r.append("pass out quick on { \(tunnels.joined(separator: " ")) } all") }
        if s.dnsOnlyTunnels { r.append("block return out quick proto { tcp udp } to any port 53") }
        if s.blockIPv6 {
            r.append("pass out quick inet6 proto icmp6 all icmp6-type { neighbrsol neighbradv routersol }")
            r.append("block return out quick inet6 all")
        }
        var seen = Set<UInt32>()
        // A user with any block that keeps the LAN closed gets the closed one.
        for owner in locks.map(\.owner).sorted() where seen.insert(owner).inserted {
            let open = locks.filter { $0.owner == owner }.allSatisfy(\.allowLAN)
            r.append(open ? "block return out quick proto { tcp udp } to ! <mugvpn_lan> user \(owner)"
                          : "block return out quick proto { tcp udp } all user \(owner)")
        }
        return r.joined(separator: "\n") + "\n"
    }

    static func isUtun(_ s: String) -> Bool {
        s.hasPrefix("utun") && s.count > 4 && s.count <= 8 && s.dropFirst(4).allSatisfy { ("0"..."9").contains($0) }
    }
}
