#!/usr/bin/env python3
"""MugVPN's string catalogs.

  tools/l10n/l10n.py keys      list the keys used in the app (L("...")) -> tools/l10n/keys.json
  tools/l10n/l10n.py build     write Resources/<lang>.lproj/Localizable.strings

A key is the English text. Translations come from tools/l10n/translations:
<lang>.json, plus common.json for keys shared by every language or added later.
Missing translations make `build` fail; Tests/Logic LOC-01, 02, 04, 05 check the result.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "Sources", "MugVPN")
RES = os.path.join(ROOT, "Resources")
TRANS = os.path.join(ROOT, "tools", "l10n", "translations")

LANGS = ["en", "cs", "de", "da", "el", "es", "fa", "fi", "fr", "it", "ja", "ko", "nl", "nb", "pl", "pt-BR", "ru", "sv",
         "tr", "uk", "zh-Hans", "zh-Hant"]


def keys():
    out = set()
    for f in sorted(os.listdir(SRC)):
        if f.endswith(".swift"):
            text = open(os.path.join(SRC, f), encoding="utf-8").read()
            for m in re.finditer(r'\bL\("((?:[^"\\]|\\.)*)"', text):
                out.add(m.group(1).replace('\\"', '"').replace("\\n", "\n").replace("\\\\", "\\"))
    return sorted(out)


def quote(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def build():
    ks = keys()
    common_all = json.load(open(os.path.join(TRANS, "common.json"), encoding="utf-8"))
    missing = {}
    for lang in LANGS:
        tfile = os.path.join(TRANS, f"{lang}.json")
        trans = json.load(open(tfile, encoding="utf-8")) if os.path.exists(tfile) else {}
        trans = {**trans, **common_all.get(lang, {})}
        lines = []
        for k in ks:
            if lang == "en":
                v = k
            elif k in trans:
                v = trans[k]
            else:
                missing.setdefault(lang, []).append(k)
                continue
            lines.append(f"{quote(k)} = {quote(v)};")
        d = os.path.join(RES, f"{lang}.lproj")
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "Localizable.strings"), "w", encoding="utf-8") as f:
            f.write("/* Generated by tools/l10n/l10n.py from tools/l10n/translations. */\n")
            f.write("\n".join(lines) + "\n")
    if missing:
        for lang, ks2 in missing.items():
            print(f"{lang}: {len(ks2)} missing: {ks2[:3]}", file=sys.stderr)
        sys.exit(1)


def list_keys():
    ks = keys()
    json.dump([{"key": k} for k in ks], open(os.path.join(ROOT, "tools", "l10n", "keys.json"), "w", encoding="utf-8"),
              ensure_ascii=False, indent=1)
    print(f"{len(ks)} keys")


if __name__ == "__main__":
    {"keys": list_keys, "build": build}[sys.argv[1] if len(sys.argv) > 1 else "build"]()
